apiVersion: v2
name: checkmate-chart
description: A Helm chart for Checkmate App
type: application
version: 0.1.0
appVersion: "2.3"
dependencies:
  - name: app-template
    alias: server
    version: 4.2.0
    repository: https://bjw-s-labs.github.io/helm-charts
    condition: server.enabled
  - name: app-template
    alias: client
    version: 4.2.0
    repository: https://bjw-s-labs.github.io/helm-charts
    condition: client.enabled
  - name: mongodb
    version: 16.5.40
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: redis
    version: 22.0.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
