client:
  enabled: true
  image:
    repository: ghcr.io/bluewave-labs/checkmate-client
    tag: v2.3
  service:
    main:
      ports:
        http:
          port: 80
  ingress:
    main:
      enabled: true
      hosts:
        - host: change_me
          paths:
            - path: /
              pathType: Prefix

server:
  enabled: true
  image:
    repository: ghcr.io/bluewave-labs/checkmate-backend
    tag: v2.3
  envFrom:
    - secretRef:
        name: checkmate-secrets
  service:
    main:
      ports:
        http:
          port: 52345
  ingress:
    main:
      enabled: true
      hosts:
        - host: change_me
          paths:
            - path: /
              pathType: Prefix

mongodb:
  enabled: true
  auth:
    enabled: false
  persistence:
    size: 5Gi

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      size: 1Gi

secrets:
  JWT_SECRET: change_me
  REFRESH_TOKEN_SECRET: change_me
  SYSTEM_EMAIL_ADDRESS: test@example.com
  SYSTEM_EMAIL_PASSWORD: change_me
  SYSTEM_EMAIL_HOST: smtp.example.com
  SYSTEM_EMAIL_PORT: "587"
  PAGESPEED_API_KEY: change_me
  DB_CONNECTION_STRING: mongodb://checkmate-mongodb:27017/uptime_db
  REDIS_HOST: checkmate-redis-master
  REDIS_PORT: "6379"
  DB_TYPE: MongoDB
  TOKEN_TTL: 99d
  REFRESH_TOKEN_TTL: 99d

