version: "3.8"

services:
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist-mono-multiarch
    restart: always
    ports:
      - "52345:52345"
    environment:
      - UPTIME_APP_API_BASE_URL=http://localhost:52345/api/v1
      - UPTIME_APP_CLIENT_HOST=http://localhost
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - CLIENT_HOST=http://localhost
      - JWT_SECRET=my_secret
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis:7
    container_name: checkmate-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.18
    restart: always
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d
