{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checkmate.client.fullname" . }}-nginx
  labels:
    {{- include "checkmate.client.labels" . | nindent 4 }}
data:
  # Only override the upstream and proxy configurations
  upstream.conf: |
    upstream checkmate_backend {
        server {{ include "checkmate.server.serviceName" . }}:{{ .Values.server.service.main.ports.http.port }};
    }
  
  proxy.conf: |
    # API documentation proxy
    location /api-docs/ {
        proxy_pass http://checkmate_backend/api-docs/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # API proxy (if needed for direct API calls)
    location /api/ {
        proxy_pass http://checkmate_backend/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
{{- end }}
