            - name: First interaction
  uses: actions/first-interaction@v1.3.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: Thanks for opening your first issue! :) # optional
    # Comment to post on an individual's first pull request
    pr-message: Thanks for creating your first PR! :)  # optional
