name: Sync Upstream (Backend)

on:
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Current Date and Day
        id: date
        run: echo "BRANCH_NAME=shadow/$(date +%A-%Y-%m-%d)" >> $GITHUB_ENV

      - name: Add Upstream Remote and Fetch Latest Changes
        run: |
          git remote add upstream https://github.com/bluewave-labs/checkmate-backend.git || true
          git fetch upstream develop --prune
          if ! git show-ref --quiet refs/remotes/upstream/develop; then
            exit 1
          fi

      - name: Create and Checkout New Shadow Branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }} develop
          git merge --no-ff upstream/develop || echo "Merge conflicts detected, resolving via PR."

      - name: Check for New Changes Before Pushing
        run: |
          if git diff --quiet develop ${{ env.BRANCH_NAME }}; then
            exit 0
          fi

      - name: Push Shadow Branch to Private Repo
        run: |
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Sync Upstream (Backend) - ${{ env.BRANCH_NAME }}"
          body: "Automated upstream sync for backend repository. Please review and resolve conflicts before merging."
          branch: ${{ env.BRANCH_NAME }}
          base: develop
          labels: "sync, upstream"
          reviewers: "ridvankaratas, ajhollid"
